#!/bin/sh

ARCH=x86-64

# detect if the CPU supports "modern" features
if cat /proc/cpuinfo | grep -q "^flags.*popcnt" ; then
    ARCH=x86-64-modern
fi

git submodule update --init
cd Stockfish/src
make build ARCH=$ARCH > /dev/null
cd ../..
