#!/bin/sh

if [ -d Stockfish/src ] && [ ! "$(git status | grep "Stockfish (new commits")" ]; then
  echo "- Stockfish is up to date"
  exit 0;
fi

if [ -f /proc/cpuinfo ]; then
  ARCH=x86-64
  # detect if the CPU supports "modern" features
  if grep -q "^flags.*popcnt" /proc/cpuinfo ; then
    ARCH=x86-64-modern
  fi
else
  ARCH=x86-64-modern
fi

echo "- Detected architecture $ARCH"

echo "- Fetching latest Stockfish..."
git submodule update --init

cd Stockfish/src
echo "- Building and profiling Stockfish..."
echo "  This will take about 2 minutes, but is only needed once."
make profile-build ARCH=$ARCH > /dev/null
cd ../..
echo "- Done!"
