#!/bin/sh

APIKEY=$1

if [ ! -f polyglot.ini ]; then
  # First run, API key is required
  if [ ! $APIKEY ]; then
    echo "Usage: ./start APIKEY"
    exit 1
  fi
  cp polyglot.ini.default polyglot.ini
fi

# If API key provided, save it in config
if [ $APIKEY ]; then
  sed -i "s/^Apikey\s=.*/Apikey = $APIKEY/g" polyglot.ini
fi

echo "Looking for fishnet updates..."
git fetch origin
git checkout stable
git merge origin/stable

echo "Looking for stockfish updates..."
./install-stockfish

echo "Starting fishnet!"
python fishnet.py polyglot.ini
