#!/bin/sh

# Unsupported servers:
# - salim2
# - hexal
# - matthews

for server in clyde bofur marta ushio flynn cammy rambo adele khiaw homer; do
  echo -e "\n"
  echo "Upgrading $server..."
  echo -e "\n"
  ssh $server "bash -s" -- < doc/recipe/prod-install
done;
