#!/bin/sh

# Usage:
# Install:
# ssh servername "bash -s" -- < doc/recipe/prod-install apikey
# Upgrade:
# ssh servername "bash -s" -- < doc/recipe/prod-install

APIKEY=$1

DIR=/home/fishnet
PYTHON=$(which python3)
REPO_URL=https://github.com/niklasf/fishnet

echo "Found python $PYTHON"

if [ ! -f "$DIR/polyglot.ini" ]; then
  INSTALL=true
  echo "Installing fishnet from scratch..."
  if [ ! $APIKEY ]; then
    echo "API key required for first install!"
  fi
else
  INSTALL=false
  echo "Upgrading fishnet..."
fi

if which apt-get > /dev/null; then
  apt-get -qq update
  apt-get install git g++ make || true
fi

useradd fishnet || true
mkdir -p $DIR
cd $DIR

git clone $REPO_URL --branch stable . 2> /dev/null || git fetch origin
git checkout stable
git merge origin/stable

echo "Installing stockfish..."
./install-stockfish

if $INSTALL; then
  cp polyglot.ini.default polyglot.ini
  config="[Fishnet]
Apikey = $APIKEY
EngineDir = $DIR/Stockfish/src/
EngineCommand = ./stockfish
Endpoint = http://en.lichess.org/fishnet/
Cores = All
Memory = 512
; Fixed Backoff = 3

[Engine]
Threads = 4
"
  echo "$config" > polyglot.ini
fi

service="# Fishnet service
[Unit]
Description=Fishnet
After=network.target

[Service]
User=fishnet
Group=fishnet
WorkingDirectory=$DIR
ExecStart=$PYTHON fishnet.py polyglot.ini
Nice=5
Restart=always

[Install]
WantedBy=multi-user.target
"
echo "$service" > /etc/systemd/system/fishnet.service
systemctl daemon-reload
systemctl enable fishnet

chown -R fishnet:fishnet $DIR

systemctl restart fishnet

echo -e "\nFishnet (re)started!"

sleep 1

journalctl -ru fishnet -n 30
